### PR TITLE
Sampling interval

### PR DESCRIPTION
**Pull request by joehoyle**
Taken from https://github.com/phacility/xhprof/pull/80, same patch but refreshed. Needs accreditation.

### CODE REVIEW

**Comment by Slach** [comment]
Failed to build with php7 sampling-interval branch with following errors
```
/opt/xhprof/extension/xhprof.c:2025:19: error: 'zval' has no member named 'type'
   } else if(values->type == IS_STRING) {
                   ^
Makefile:193: recipe for target 'xhprof.lo' failed
make: *** [xhprof.lo] Error 1
```

full log here
https://pastebin.com/mheCFree
;(

**Comment by nathanielks** [comment]
I'm curious why the tests were removed?

**Comment by nathanielks** [comment]
Excuse me, it was just one test file! Nevermind!

**Comment by joehoyle** [comment]
@nathanielks this PR had the wrong base, I've updated that now, but it wasn't intended to be merged anyway.

**Comment by nathanielks** [comment]
I'll leave it be 😄

**Comment by rmccue** [comment]
@joehoyle I feel like we should just merge this and start maintaining it as a full repo, given we're running in production.

**Comment by rmccue** [comment]
And by "merge this" I mean, merge `sampling-interval` into `experimental`, and merge `experimental` into `master`. I'd say we should probably also rip out the non-`extension` directories.

I can get in touch with Phacility again if we want?

**Comment by joehoyle** [comment]
@rmccue yeah I think that's a good idea. No idea what Phacility are doing! 

Also, MediaWiki it looks like chose not to go this route as they were seeing large overheads, which I have not been able to replicate (see https://phabricator.wikimedia.org/T176916). They are exploring other ways to instrument function enter / exits. It's worth us continuing to monitor what solution they come up with as we are essentially wanting to do the same thing (low-overhead flame graphs)

**Pull request closed without merging**
